services:
  db:
    image: postgres:16
    container_name: apostas-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: apostas
      POSTGRES_USER: apostas_user
      POSTGRES_PASSWORD: apostas_pass
      TZ: America/Sao_Paulo
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apostas_user -d apostas"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: sistema_apostas
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://apostas_user:apostas_pass@db:5432/apostas
      TZ: America/Sao_Paulo
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pg_data:
