services:
  db:
    image: mysql:8.0
    container_name: apostas-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: apostas
      MYSQL_USER: apostas_user
      MYSQL_PASSWORD: apostas_pass
      TZ: America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapostas_user", "-papostas_pass"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: sistema_apostas
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://apostas_user:apostas_pass@db:3306/apostas
      TZ: America/Sao_Paulo
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  db_data:
